### ISSUE TITLE
Xbyak::Error, x2APIC not supported on MacOS

### ISSUE THREAD

**Issue by inspirewind** [kellylab/viral-protein-function-plm#3]
hello developers,

When I trying to run the provided `test.sh` script from the project, the program terminates unexpectedly and throws the following error:

> libc++abi: terminating with uncaught exception of type Xbyak::Error: x2APIC is not supported
> test.sh: line 11: 68868 Abort trap: 6 python scripts/predict_function.py -faa test/test.faa -out test_out --output_predictions --prediction_heatmap --output_embeddings --efam_calibration_threshold

This error seems to point to an issue with the `Xbyak` library, indicating that `x2APIC` is not supported. I am using the arm architecture m2 pro processor and confirmed that I created an osx-64 conda environment。

## Environment

- Operating System: macOS 13.2
- conda Version: 

>  active environment : plm_vpf_predict
>     active env location : /Users/inspirewind/miniconda3/envs/plm_vpf_predict
>             shell level : 2
>        user config file : /Users/inspirewind/.condarc
>  populated config files : /Users/inspirewind/.condarc
>           conda version : 23.3.1
>     conda-build version : not installed
>          python version : 3.11.3.final.0
>        virtual packages : __archspec=1=x86_64
>                           __osx=13.2=0
>                           __unix=0=0
>        base environment : /Users/inspirewind/miniconda3  (writable)
>       conda av data dir : /Users/inspirewind/miniconda3/etc/conda
>   conda av metadata url : None
>            channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-64
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/osx-64
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/osx-64
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/osx-64
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/osx-64
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/osx-64
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
>           package cache : /Users/inspirewind/miniconda3/pkgs
>                           /Users/inspirewind/.conda/pkgs
>        envs directories : /Users/inspirewind/miniconda3/envs
>                           /Users/inspirewind/.conda/envs
>                platform : osx-64
>              user-agent : conda/23.3.1 requests/2.31.0 CPython/3.11.3 Darwin/22.3.0 OSX/13.2
>                 UID:GID : 501:20
>              netrc file : None
>            offline mode : False

Thank you for your time and assistance!

**Comment by lynceuslq** [comment]
Hi inspirewind, I also struggled with the problem quite a while and found out that the problem was with wrong Tensorflow and Keras installation on MacBook M1 chip.  To solve this, you can download miniforge3 for arm64 with the link https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh and install it on you Mac, then use the conda commands from you miniforge3 to create "plm_vpf_predict" environment, like 
`~/miniforge3/bin/conda env create -f plm_vpf_predict.yml` and run the prediction task with 
`~/miniforge3/envs/plm_vpf_predict/bin/python  scripts/predict_function.py -faa test/test.faa -out test_out --output_predictions --prediction_heatmap --output_embeddings --efam_calibration_threshold`. And you should find the output files in the "test_out" directory. 

But for the embedding step, please don't delete your original intel conda, as you can only install "plm_vpf_embed" environment with that conda because miniforge3 for arm64 only support python >= 3.8. 

I hope you find it helpful!
